export const SIDEBAR_TEST_IDS = {
	USER_FULL_NAME: 'sidenav-user-full-name',
	USERNAME: 'sidenav-username',
	USER_BALANCE: 'sidenav-user-balance',
	ACCOUNT_BALANCE_LABEL: 'sidenav-account-balance',
	HOME_LINK: 'sidenav-home',
	USER_SETTINGS_LINK: 'sidenav-user-settings',
	BANK_ACCOUNTS_LINK: 'sidenav-bankaccounts',
	NOTIFICATIONS_LINK: 'sidenav-notifications',
	SIGNOUT_BUTTON: 'sidenav-signout',
	PERSON_ICON: 'PersonIcon',
	ACCOUNT_BALANCE_ICON: 'AccountBalanceIcon',
	NOTIFICATIONS_ICON: 'NotificationsIcon',
	EXIT_TO_APP_ICON: 'ExitToAppIcon',
};
